version: '3'

services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    image: warehouseapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data: